### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [Wirecloud/wirecloud#487]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.3.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary wirecloud -w /tmp/ext wirecloud==1.3.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting wirecloud==1.3.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/b7b/0a62271f9abc0/wirecloud-1.3.1.tar.gz (11.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-1pmbp1gs/wirecloud/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-1pmbp1gs/wirecloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-1pmbp1gs/wirecloud/pip-egg-info
         cwd: /tmp/pip-wheel-1pmbp1gs/wirecloud/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-1pmbp1gs/wirecloud/setup.py", line 163, in <module>
        long_description=read('../README.md'),
      File "/tmp/pip-wheel-1pmbp1gs/wirecloud/setup.py", line 152, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-1pmbp1gs/wirecloud/../README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
I can't really make sense of how this is built; the problem appears to be that the readme is out of the directory that gets included.
