### ISSUE TITLE
WireCloud unusable after installing django-compressor 2.0+

### ISSUE THREAD

**Issue by aarranz** [Wirecloud/wirecloud#95]
django-compressor 2.0 dropped support for Django 1.4-1.7.

WireCloud 0.9.0 will support Django 1.7-1.9 (see #84, #85 and #86) but the new release of WireCloud for the 0.8.x serie (0.8.3) should indicate that it requires django-compressor < 2.0.

**Comment by aarranz** [comment]
For the records, this is an example of the exception raised when using django-compressor 2.0+:

```pytb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/var/lib/jenkins/jobs/wirecloud-pip-develop-python2.7/workspace/virtenv/local/lib/python2.7/site-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils
Error: Error executing external command
```
